### ISSUE TITLE
Error when generating schema from CSV file

### ISSUE THREAD

**Issue by jmcastagnetto** [frictionlessdata/tableschema-r#17]
Tried a slightly modified version of the example code in the documentation for the `datapackage.r` package, using the data at `https://github.com/jmcastagnetto/peru-candidatos-2021-infofinanciera/raw/main/datos/proc/candidatos-2021-bienes-ingresos.csv`, and it fails with the error: `Error: missing value where TRUE/FALSE needed`

This is the code I am using:

```
library(datapackage.r)

data_package <- Package.load()
data_package$descriptor["name"] <- "elecciones-2021-candidatos-infofinanciera"
data_package$descriptor["title"] <- "Elecciones Generales 2021 (Perú): Información financiera de los candidatos al congreso"
data_package$commit()
csv <- "https://github.com/jmcastagnetto/peru-candidatos-2021-infofinanciera/raw/main/datos/proc/candidatos-2021-bienes-ingresos.csv" 
schm <- tableschema.r::infer(csv)  # this is the line that generates the error
```

I wasn't able to find an error message like the one I get, in your package code. Looked in https://github.com/frictionlessdata/tableschema-r/blob/ee85b22290009c40b4b79fee99aed9850f6a3a87/R/infer.R, https://github.com/frictionlessdata/tableschema-r/blob/ee85b22290009c40b4b79fee99aed9850f6a3a87/R/table.R#L169 and https://github.com/frictionlessdata/tableschema-r/blob/ee85b22290009c40b4b79fee99aed9850f6a3a87/R/schema.R

As a reference, here is my `sessionInfo()` output

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] datapackage.r_1.3.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5          rstudioapi_0.13     parallelly_1.22.0  
 [4] magrittr_2.0.1      hms_0.5.3           rsthemes_0.1.0     
 [7] jsonvalidate_1.1.0  R6_2.5.0            rlang_0.4.10       
[10] stringr_1.4.0       tableschema.r_1.1.1 globals_0.14.0     
[13] tools_4.0.3         parallel_4.0.3      config_0.3.1       
[16] iterators_1.0.13    yaml_2.2.1          digest_0.6.27      
[19] purrr_0.3.4         bitops_1.0-6        vctrs_0.3.6        
[22] codetools_0.2-18    RCurl_1.98-1.2      curl_4.3           
[25] V8_3.4.0            stringi_1.5.3       compiler_4.0.3     
[28] jsonlite_1.7.2      future_1.21.0       listenv_0.8.0      
[31] pkgconfig_2.0.3 
``` 

---

Please preserve this line to notify @kleanthisk10 (lead of this repository)

**Comment by kleanthisk10** [comment]
Thank you for providing the appropriate information.
You can use the validator for your data: https://goodtables.io/

It seems that there is duplicate row (288-289). If you delete duplicates it will fix this error.

http://try.goodtables.io/?source=https%3A%2F%2Fgithub.com%2Fjmcastagnetto%2Fperu-candidatos-2021-infofinanciera%2Fraw%2Fmain%2Fdatos%2Fproc%2Fcandidatos-2021-bienes-ingresos.csv&apiJobId=f254fd98-4b03-11eb-bed4-02cd6ba11d04

**Comment by jmcastagnetto** [comment]
Did not know that service you got, it is cool and useful.

Fixed the issue with the duplicated rows, and checked (just in case) afterwards and before pushing to my repo:

```
> d1 <- read_csv("datos/proc/candidatos-2021-bienes-ingresos.csv")
> nrow(d1)
[1] 3315
> d2 <- d1 %>% distinct()
> nrow(d2)
[1] 3315
```

The CSV now seems to pass the checks at gootables.io (registered there to get this):

![image](https://user-images.githubusercontent.com/364668/103393212-94432680-4aef-11eb-8813-02d6be8d2968.png)

Just to be thorough, checked with `csvlint` (from https://github.com/Clever/csvlint) and using https://csvlint.io (see: https://csvlint.io/validation/5fed497dc7e87e000400001b), and it validates OK, except for the warnings due to NAs.

Still, the problem persists with the code I showed before. Trying to narrow it down, it might be in the `read()` method:

```
t1 <- tableschema.r::Table.load(csv)
d <- future::value(t1)
v <- d$read()  # this line generates the same error as before: "Error: missing value where TRUE/FALSE needed"
```

Finally, tried using subsets of the CSV file.

Initially trying the first 110 lines (because it looks like the `infer()` method looks at the first 100 records by default), and that caused a new problem.

```
$ head -110 candidatos-2021-bienes-ingresos.csv > dtest.csv
$ R
> csv <- "dtest.csv" 
> schm <- tableschema.r::infer(csv)
Error in charToDate(x) : 
  character string is not in a standard unambiguous format
```

The only date field in the CSV is in ISO (YYYY-MM-DD) format, so I am baffled by that error.

Using the first 2500 lines:

```
$ head -2500 candidatos-2021-bienes-ingresos.csv > dtest.csv
$ R
> csv <- "dtest.csv" 
> schm <- tableschema.r::infer(csv)
Error: missing value where TRUE/FALSE needed
```

Using only 2000, got back the date parsing error:

```
$ head -2000 candidatos-2021-bienes-ingresos.csv > dtest.csv
$ R
> csv <- "dtest.csv" 
> schm <- tableschema.r::infer(csv)
Error in charToDate(x) : 
  character string is not in a standard unambiguous format
```

Long story short, after iterating manually, saw that using 2086 lines I get the "TRUE/FALSE" error, and with 2085 lines I get the date parsing error:

```
$ head -2086 candidatos-2021-bienes-ingresos.csv > dtest.csv
$ R
> csv <- "dtest.csv" 
> schm <- tableschema.r::infer(csv)
Error: missing value where TRUE/FALSE needed
> q()
$ head -2085 candidatos-2021-bienes-ingresos.csv > dtest.csv
$ R
> csv <- "dtest.csv" 
> schm <- tableschema.r::infer(csv)
Error in charToDate(x) : 
  character string is not in a standard unambiguous format
```

Just for reference, the line that causes the error seems to be:

```
08260900,D'MEDINA,EUGENIO GERALD DARIO,1962-05-04,1,140101,LIMA,LIMA,LIMA,140102,LIMA,LIMA,ANCON,AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL,1,5000,0,30000,0,0,0,0,30000,Hombre
```

So I thought that, perhaps, the apostrophe in the name was causing trouble with the parsing, so I forced all strings and factors to be quoted:

```
"2085","08260900","D'MEDINA","EUGENIO GERALD DARIO",1962-05-04,"1","140101","LIMA","LIMA","LIMA","140102","LIMA","LIMA","ANCON","AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL",1,5000,0,30000,0,0,0,0,30000,"Hombre" 
```

And then tried again 2086 lines from the (now char quoted) CSV:

```
$ head -2086 candidatos-2021-bienes-ingresos.csv > dtest.csv
$ R
> csv <- "dtest.csv" 
> schm <- tableschema.r::infer(csv)
Error: missing value where TRUE/FALSE needed
```

Maybe there is an overflow or similar issue in an internal structure?

Hope that the rambling stuff above can be of help identifying the issue.
