### ISSUE TITLE
Publish tableschema-r on CRAN

### ISSUE THREAD

**Issue by serahkiburu** [frictionlessdata/tableschema-r#7]
https://discuss.okfn.org/t/is-getting-tableschema-r-on-cran-a-goal-for-that-repo-package/7249

**Comment by serahkiburu** [comment]
@kleanthisk10, thanks for addressing https://github.com/frictionlessdata/datapackage-r/issues/17. Will you be submitting this tableschema-r to C-RAN as well?

**Comment by kleanthisk10** [comment]
@serahrono yes of course!

**Comment by serahkiburu** [comment]
Thanks for getting this done, @kleanthisk10 
https://cran.r-project.org/package=tableschema.r 🎉
