### ISSUE TITLE
Problem with records that contain quoted commas

### ISSUE THREAD

**Issue by decisionmechanics** [frictionlessdata/tableschema-r#9]
Validation seems to be failing when (quoted) fields in the CSV contain commas. e.g.

```
id,text
123,"This, is, some, text"
```

Error is

```
Error: Row dimension doesn't match schema's fields dimension
```

**Comment by kleanthisk10** [comment]
Can you provide more details (with code)?

**Comment by decisionmechanics** [comment]
Sure.

CSV file (`countries.csv`):

```
country_code,name
BES,"Bonaire, Sint Eustatius and Saba"
```

Schema (`country_table_schema.json`):

```
{
    "fields": [{
            "name": "country_code"
        },
        {
            "name": "name"
        }
    ]
}
```

R script:

```
library(tableschema.r)

csv <- "countries.csv"
schema <- "country_table_schema.json"

def <- Table.load(csv, schema = schema, strict = TRUE)
table <- def$result$value
table$read()
```

Output:

```
Error: Row dimension doesn't match schema's fields dimension
```

**Comment by kleanthisk10** [comment]
Ηaving a schema:

```
schema = '{
    "fields": [{
            "name": "country_code"
        },
        {
            "name": "name"
        }
    ]
}' 
```

**1.** So far the only way to do such was to have instead of csv provide a json array:

```source = 
'
[
     ["country_code", "name"],
     ["BES", "Bonaire, Sint Eustatius and Sab"]
]
'
```

Rscript:
```
def <- Table.load(helpers.from.json.to.list(SOURCE), schema = schema, strict = TRUE)
table <- future::value(def)
table$read()
```
**2.** The other choice is to change your delimiter to `";"`  (need to re-install tableschema.r)

CSV file (countries.csv):

```
country_code;name
BES;"Bonaire, Sint Eustatius and Saba"
```

Rscript:

```
schema =  '{
    "fields": [{
            "name": "country_code"
        },
        {
            "name": "name"
        }
    ]
}' 

csv <- "countries.csv"

def <- Table.load(csv, schema = schema, strict = TRUE)
table <- future::value(def)
table$read()
```

**Comment by sakrejda** [comment]
@kleanthisk10 I don't understand your response.  What's the root cause for this problem? Is this just difficult to fix due to some issue with R or .csv formats or is it outside of the scope of the package?

**Comment by sakrejda** [comment]
We'd _like_ to use the package for a bigger project but need to find out if it covers our use case (validating input .csv files produced by collaborators).

**Comment by kleanthisk10** [comment]
The root problem was when reading row by row couldn't ignore delimiter inside quotes and that's why i proposed two alternatives. It's fixed now you should re-install tableschema.r package.
Thank you!
